### ISSUE TITLE
Docker HealthCheck

### ISSUE THREAD

**Issue by Ezka77** [Ezka77/xen-orchestra-ce#22]
Enable Docker healthcheck
```
    healthcheck:
        test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8000"]
        interval: 1m30s
        timeout: 10s
        retries: 3
```
